export const LANDING_SERVICES = [
  {
    id: 1,
    name: "Contract Farming",
    point1: "Access to Resources",
    point2: "Flexibility and Efficiency",
    point3: "Types of Agreements",
    icon: "/contract.svg",
    link: "/services",
  },
  {
    id: 2,
    name: "Rentals",
    point1: "Access modern machinery on-demand",
    point2: "Transparent, flexible daily rentals",
    point3: "Verified tools and equipment",
    icon: "/rentals.svg",
    link: "/services",
  },
  {
    id: 3,
    name: "Transport Services",
    point1: "Reliable logistics from farm to market",
    point2: "Scheduled and on-demand pickups",
    point3: "Fair, transparent freight rates",
    icon: "/transport.svg",
    link: "/services",
  },
  {
    id: 4,
    name: "Fertilizers & Shop",
    point1: "High-grade certified inputs",
    point2: "Affordable seed and fertilizer options",
    point3: "Direct delivery to your doorstep",
    icon: "/fertilizers.svg",
    link: "/services",
  },
];

export const AI_TOOLKIT_PREVIEWS = [
  {
    id: 1,
    name: "Crop Yield Prediction",
    desc: "Forecast your expected harvest output by analyzing crop varieties, acreage, and seasonal parameters.",
    point1: "Analyze regional historical yield trends",
    point2: "Input specific cultivation acreage and seasons",
    point3: "Plan storage and logistics with confidence",
    icon: "/yield.svg",
  },
  {
    id: 2,
    name: "Crop Price Prediction",
    desc: "Estimate market commodity valuations using mandi arrival volumes and current market codes.",
    point1: "Track mandi arrivals and price movements",
    point2: "Plan the best sales timing for your harvest",
    point3: "Compare commodity varieties across states",
    icon: "/prize.svg",
  },
  {
    id: 3,
    name: "Crop Disease Detection",
    desc: "Upload leaf photographs to inspect disease indicators and review actionable remedies.",
    point1: "Instant symptom analysis with computer vision",
    point2: "Diagnose viral, fungal, and pest infections",
    point3: "Targeted organic and chemical treatment advice",
    icon: "/disease.svg",
  },
  {
    id: 4,
    name: "Crop Recommendation",
    desc: "Derive proxy NPK and pH levels from classified soil images paired with live weather inputs.",
    point1: "Classify soil type directly from photos",
    point2: "Incorporate live GPS temperature and rainfall",
    point3: "Receive data-driven recommendations on best-fit crops",
    icon: "/best.svg",
  },
];